/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Healthcheck. Distingue "arranco" de "arranco con modelo".
         *
         *     Es tambien el endpoint del que la interfaz deriva su estado global: que capa de
         *     datos se esta sirviendo, si el toggle de censura tiene las dos bases cargadas y
         *     cuanta de la cobertura prometida se cumple de verdad.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Series
         * @description Series disponibles, con busqueda y paginacion. Es el selector de la interfaz.
         *
         *     Devuelve `total` aparte de la pagina porque el selector muestra el conteo de
         *     resultados sobre el total: con 3066 series un desplegable no es usable y el
         *     usuario necesita saber si lo que busca esta filtrado o no existe.
         *
         *     La busqueda corre sobre el codigo de la serie y sobre la jerarquia. Como el
         *     dataset no trae nombres de producto, la jerarquia es una lista de ids, asi que
         *     un numero suelto ("2") tambien aparece en el producto o en la categoria y la
         *     busqueda trae de mas. Para filtrar con precision esta `store_id`; la busqueda
         *     esta para descubrir. Con nombres de producto esto se resolveria solo, pero
         *     inventarlos seria inventar datos.
         */
        get: operations["list_series_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{series_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Series History
         * @description Venta observada contra demanda latente, dia por dia, con los tramos de quiebre.
         *
         *     Es el endpoint de la pantalla principal y el unico lugar de la API donde las
         *     dos series se devuelven juntas. Van juntas a proposito: el argumento del
         *     proyecto es la **brecha** entre ellas, y dos llamadas separadas invitan a
         *     dibujarlas desalineadas o a comparar rangos de fechas distintos.
         *
         *     En los dias sin quiebre las dos series son identicas por diseno, no por
         *     casualidad: son la verdad de terreno con la que se mide el sesgo, asi que
         *     corregirlas destruiria la medicion. `summary.uplift_pct_clean_days` lo
         *     devuelve como comprobacion, y tiene que dar 0.
         */
        get: operations["series_history_series__series_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Series History Batch
         * @description La misma historia para varias series de una vez.
         *
         *     Existe porque la pantalla de reposicion la necesita **por fila**: el sparkline
         *     de quiebre de los ultimos 14 dias y la comparacion contra la politica de media
         *     movil salen de la historia, no del pronostico. Una llamada por fila seria un
         *     N+1 contra un panel que ya esta en memoria.
         */
        post: operations["series_history_batch_series_history_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Forecast
         * @description Pronostico con intervalo, si el modelo cargado esta conformalizado.
         *
         *     `recover_censoring` elige el artefacto: el entrenado sobre demanda latente o el
         *     entrenado sobre venta observada. Es un modelo distinto y no un ajuste del
         *     mismo, porque el sesgo de la censura se aprende durante el entrenamiento —
         *     corregir la salida despues seria inventar el efecto que el proyecto mide.
         */
        post: operations["forecast_forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reorder
         * @description Cantidad a reponer: el cuantil critico del newsvendor.
         *
         *     La salida del modelo **es** la orden. No es un pronostico que alguien tenga que
         *     interpretar y despues ajustar a mano con un stock de seguridad.
         */
        post: operations["reorder_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtest
         * @description Metricas del ultimo backtest, con dispersion entre origenes.
         *
         *     Lee `reports/backtest_models.parquet`, que produce `make models`. No corre el
         *     backtest en el request: son minutos de entrenamiento y una API no es el lugar.
         */
        get: operations["backtest_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/censoring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Censoring
         * @description Resumen de censura del panel: observado contra latente recuperado.
         */
        get: operations["censoring_censoring_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestResponse */
        BacktestResponse: {
            /** Target */
            target: string;
            /** Horizon */
            horizon: number;
            /** Season Length */
            season_length: number;
            /** Rows */
            rows: components["schemas"]["MetricRow"][];
            external_baseline?: components["schemas"]["MetricRow"] | null;
        };
        /**
         * Basis
         * @description Base de calculo. Es el vocabulario del toggle de la interfaz (`?basis=`).
         *
         *     No reemplaza a `recover_censoring` en los requests: ese nombre ya esta en el
         *     contrato y renombrarlo seria un rename en tres lugares mas. El booleano
         *     entra, la base sale — asi la respuesta dice con que artefacto se contesto.
         * @enum {string}
         */
        Basis: "observed" | "recovered";
        /**
         * CoveragePoint
         * @description Cobertura empirica de un paso del horizonte contra la nominal.
         *
         *     La degradacion **no** es monotona y eso es correcto: con estacionalidad
         *     semanal el objetivo de h7 cae el mismo dia de la semana que el origen.
         */
        CoveragePoint: {
            /** H */
            h: number;
            /** Coverage Nominal */
            coverage_nominal: number;
            /** Coverage Empirical */
            coverage_empirical: number;
            /** N */
            n: number;
        };
        /** ForecastPoint */
        ForecastPoint: {
            /**
             * Dt
             * Format: date
             */
            dt: string;
            /** H */
            h: number;
            /** Y Pred */
            y_pred: number;
            /** Pred Lo */
            pred_lo?: number | null;
            /** Pred Hi */
            pred_hi?: number | null;
        };
        /** ForecastRequest */
        ForecastRequest: {
            /** Series Ids */
            series_ids: string[];
            /**
             * Horizon
             * @default 7
             */
            horizon: number;
            /**
             * Coverage
             * @default 0.9
             */
            coverage: number;
            /**
             * Recover Censoring
             * @default true
             */
            recover_censoring: boolean;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Model Name */
            model_name: string;
            basis: components["schemas"]["Basis"];
            /** Coverage Nominal */
            coverage_nominal: number;
            /** Coverage Empirical */
            coverage_empirical?: number | null;
            /** Forecasts */
            forecasts: components["schemas"]["SeriesForecast"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Respuesta de /health. Sirve para el healthcheck de Docker Compose.
         */
        Health: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
            /** Model Loaded */
            model_loaded: boolean;
            /** Model Name */
            model_name?: string | null;
            /** Trained Until */
            trained_until?: string | null;
            /** Model Error */
            model_error?: string | null;
            /**
             * Models
             * @default []
             */
            models: components["schemas"]["ModelStatus"][];
            panel?: components["schemas"]["PanelInfo"] | null;
            /** Coverage Nominal */
            coverage_nominal?: number | null;
            /**
             * Coverage By Horizon
             * @default []
             */
            coverage_by_horizon: components["schemas"]["CoveragePoint"][];
            /** Coverage Note */
            coverage_note?: string | null;
        };
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Dt
             * Format: date
             */
            dt: string;
            /** Observed */
            observed: number;
            /** Recovered */
            recovered: number;
            /** Is Censored */
            is_censored: boolean;
            /** Oos Hours Open */
            oos_hours_open: number;
            /** Available Weight */
            available_weight?: number | null;
            /** Inflation Factor */
            inflation_factor?: number | null;
        };
        /** HistorySummary */
        HistorySummary: {
            /** N Days */
            n_days: number;
            /** N Censored Days */
            n_censored_days: number;
            /** Censored Days Last 28 */
            censored_days_last_28: number;
            /** Share Censored Days */
            share_censored_days: number;
            /** Max Run Days */
            max_run_days: number;
            /** Mean Oos Hours When Censored */
            mean_oos_hours_when_censored?: number | null;
            /** Uplift Pct */
            uplift_pct: number;
            /** Uplift Pct Clean Days */
            uplift_pct_clean_days: number;
        };
        /**
         * MetricRow
         * @description Una metrica de un modelo, con dispersion entre origenes.
         *
         *     `std` no es opcional por diseno: la metodologia del proyecto prohibe
         *     reportar un numero unico, porque un promedio bueno esconde un origen
         *     catastrofico.
         */
        MetricRow: {
            /** Model Name */
            model_name: string;
            /** Metric */
            metric: string;
            /** Mean */
            mean: number;
            /** Std */
            std: number;
            /** Worst Origin */
            worst_origin: number;
            /** Best Origin */
            best_origin: number;
            /** N Origins */
            n_origins: number;
        };
        /**
         * ModelStatus
         * @description Estado de un artefacto. Hay uno por base de calculo.
         *
         *     `n_series_seen` contra `n_series_in_panel` existe porque el desajuste
         *     train/serve que ninguna metrica detecta es servir un artefacto entrenado
         *     sobre `data/sample/` contra el panel completo. Paso en este proyecto.
         */
        ModelStatus: {
            basis: components["schemas"]["Basis"];
            /** Artifact */
            artifact: string;
            /** Loaded */
            loaded: boolean;
            /** Model Name */
            model_name?: string | null;
            /** Target */
            target?: string | null;
            /** Trained Until */
            trained_until?: string | null;
            /** N Series Seen */
            n_series_seen?: number | null;
            /** N Series In Panel */
            n_series_in_panel?: number | null;
            /** Error */
            error?: string | null;
        };
        /**
         * PanelInfo
         * @description Que datos se estan sirviendo. Dispara el estado de muestra de la interfaz.
         *
         *     Los conteos van **siempre contra su referencia**: "60 de 3066 series" dice
         *     algo, "60 series" no. La referencia sale del manifiesto del submuestreo, asi
         *     que es `None` si no esta — y en ese caso la interfaz no puede afirmar que
         *     esta viendo el panel completo.
         */
        PanelInfo: {
            /**
             * Source
             * @enum {string}
             */
            source: "processed" | "sample";
            /** Is Sample */
            is_sample: boolean;
            /** N Series */
            n_series: number;
            /** N Stores */
            n_stores: number;
            /** N Products */
            n_products: number;
            /** N Days */
            n_days: number;
            /**
             * Date Min
             * Format: date
             */
            date_min: string;
            /**
             * Date Max
             * Format: date
             */
            date_max: string;
            /** Reference N Series */
            reference_n_series?: number | null;
            /** Reference N Stores */
            reference_n_stores?: number | null;
            /** Reference N Products */
            reference_n_products?: number | null;
        };
        /** ReorderLine */
        ReorderLine: {
            series: components["schemas"]["SeriesRef"];
            /**
             * Dt
             * Format: date
             */
            dt: string;
            /** Qty */
            qty: number;
            /** Critical Fraction */
            critical_fraction: number;
            /** Expected Shortfall */
            expected_shortfall: number;
            /** Expected Overage */
            expected_overage: number;
            /** Cost Delta Pct */
            cost_delta_pct: number;
        };
        /** ReorderRequest */
        ReorderRequest: {
            /** Series Ids */
            series_ids: string[];
            /**
             * Horizon
             * @default 7
             */
            horizon: number;
            /**
             * Cu
             * @default 1
             */
            cu: number;
            /**
             * Co
             * @default 0.6
             */
            co: number;
            /**
             * Recover Censoring
             * @default true
             */
            recover_censoring: boolean;
        };
        /** ReorderResponse */
        ReorderResponse: {
            /** Critical Fraction */
            critical_fraction: number;
            basis: components["schemas"]["Basis"];
            /** Model Name */
            model_name: string;
            /** Lines */
            lines: components["schemas"]["ReorderLine"][];
            /** Total Cost Delta Pct */
            total_cost_delta_pct: number;
        };
        /** SeriesForecast */
        SeriesForecast: {
            series: components["schemas"]["SeriesRef"];
            /** Points */
            points: components["schemas"]["ForecastPoint"][];
        };
        /** SeriesHistory */
        SeriesHistory: {
            series: components["schemas"]["SeriesRef"];
            /** Open Hours */
            open_hours: number;
            /** Points */
            points: components["schemas"]["HistoryPoint"][];
            /** Runs */
            runs: components["schemas"]["StockoutRun"][];
            summary: components["schemas"]["HistorySummary"];
        };
        /** SeriesHistoryBatch */
        SeriesHistoryBatch: {
            /** Series */
            series: components["schemas"]["SeriesHistory"][];
        };
        /**
         * SeriesHistoryRequest
         * @description Historia de varias series. Es lo que pide la tabla de reposicion por fila.
         */
        SeriesHistoryRequest: {
            /** Series Ids */
            series_ids: string[];
            /** Days */
            days?: number | null;
        };
        /**
         * SeriesItem
         * @description Serie con su jerarquia de catalogo, para el selector.
         *
         *     FreshRetailNet-50K **no trae nombres de producto**: la jerarquia son ids
         *     numericos. Asi que la "descripcion" que muestra y busca el selector es la
         *     jerarquia formateada, no un nombre comercial que el dataset no tiene.
         *     Inventar nombres seria mas lindo y seria falso.
         */
        SeriesItem: {
            /**
             * Series Id
             * @example 12_403
             */
            series_id: string;
            /** Store Id */
            store_id: number;
            /** Product Id */
            product_id: number;
            /** City Id */
            city_id?: number | null;
            /** Management Group Id */
            management_group_id?: number | null;
            /** First Category Id */
            first_category_id?: number | null;
            /** Second Category Id */
            second_category_id?: number | null;
            /** Third Category Id */
            third_category_id?: number | null;
            /** Label */
            label: string;
        };
        /**
         * SeriesPage
         * @description Pagina de resultados del selector.
         *
         *     Trae `total` porque el diseno muestra el conteo de resultados sobre el total
         *     y porque 3066 series no entran en un desplegable.
         */
        SeriesPage: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Query */
            query?: string | null;
            /** Items */
            items: components["schemas"]["SeriesItem"][];
        };
        /**
         * SeriesRef
         * @description Referencia a una serie tienda-producto.
         */
        SeriesRef: {
            /**
             * Series Id
             * @example 12_403
             */
            series_id: string;
            /** Store Id */
            store_id: number;
            /** Product Id */
            product_id: number;
            /** City Id */
            city_id?: number | null;
        };
        /**
         * StockoutRun
         * @description Racha de dias consecutivos con quiebre. Es el sombreado del grafico.
         *
         *     Se entregan los tramos ya agrupados y no solo la bandera por dia porque el
         *     grafico necesita el tramo como unidad: una racha de un dia se dibuja con
         *     ancho minimo, y la mediana del panel real es de 2 dias.
         */
        StockoutRun: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
            /** N Days */
            n_days: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_series_series_get: {
        parameters: {
            query?: {
                /** @description busqueda incremental sobre el codigo de la serie y su jerarquia. Varias palabras se combinan con AND */
                q?: string | null;
                /** @description filtra por tienda */
                store_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_history_series__series_id__history_get: {
        parameters: {
            query?: {
                /** @description ultimos N dias; por defecto toda la historia */
                days?: number | null;
            };
            header?: never;
            path: {
                /** @description id de la serie, '<store_id>_<product_id>' */
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_history_batch_series_history_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesHistoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesHistoryBatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_forecast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForecastRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReorderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_backtest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
        };
    };
    censoring_censoring_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
